const PropertiesReader = require('properties-reader');

const properties = PropertiesReader('./reliance.properties');

const Propertiesrel = {
  QA_URL: properties.get('url'),
  UAT_URL: properties.get('uat_url'),
  usernamefiledW: properties.get('unfieldweb'),
  passfieldW: properties.get('pwfieldweb'),
  usernameW: properties.get('usernameweb'),
  passwordW: properties.get('passwordweb'),
  signinw: properties.get('signinweb'),
  Sidebar: properties.get('sidebar'),
  PRD : properties.get("prd"),
  Create_PRD: properties.get('create_prd'),
  Upload: properties.get('upload'),
  Select_file: properties.get('select_file'),
  Finish_btn: properties.get('finish_btn'),
  File_status: properties.get('status_file'),
  Package: properties.get('apk_pack'),
  APK_userfield: properties.get('apk_urfield'),
  APK_user: properties.get('usernameapk'),
  APK_passfield: properties.get('apk_passwordfield'),
  APK_pass: properties.get('passwordapk'),
  APK_signin: properties.get('apk_signin'),
  UAT_APK_USERFIELD: properties.get('uat_urfield'),
  UAT_APK_USER: properties.get('uatapkuser'),
  UAT_APK_PASSFIELD: properties.get('uat_passfield'),
  UAT_APK_PASSWORD: properties.get('uatapkpass'),
  UAT_Signin: properties.get('uat_apk_signin'),
  Item_inward: properties.get('inward'),
  Search_field: properties.get('search'),
  Article_id_field: properties.get('arti_field'),
  Confirm: properties.get('confirm'),
  Serail_field: properties.get('serail_filed'),
  GradeItem: properties.get('grade'),
  CheckBox1: properties.get('checkbox1'),
  CheckBox2: properties.get('checkbox2'),
  CheckBox3: properties.get('checkbox3'),
  Next: properties.get('next'),
  Missing: properties.get('missing'),
  None1: properties.get('none1'),
  Ok: properties.get('ok'),
  Defective: properties.get('defective'),
  Complete: properties.get('complete'),
  Proceed: properties.get('proceed'),
  Tag_filed: properties.get('tag_filed'),
  AddItem: properties.get('add_item'),
  CompleteIRD: properties.get('completeird'),
  Activity: properties.get('activity'),
  GenerateGRN: properties.get('generategrn'),
};
module.exports = Propertiesrel;
